config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#homepage'

  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :my_places_lists, only: [:new, :create, :show, :edit, :update]
  end

  resources :places, only: [:index, :new, :create, :show] do
    resources :comments, only: [:index, :new, :create]
  end

  resources :continents, only: [:show]

  resources :categories, only: [:show]

  namespace 'admin' do
    resources :places
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/about', to: 'pages#about'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence:true
  validates :name, uniqueness:true

  has_many :places
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :title, :body, :user_id, :place_id, presence: true
  belongs_to :user
  belongs_to :place
end

app/models/continent.rb
class Continent < ActiveRecord::Base
  validates :name, presence:true
  validates :name, uniqueness:true

  has_many :places
end

app/models/my_places_list.rb
class MyPlacesList < ActiveRecord::Base
  validates :user_id, :place_id, :visited, presence: true
  belongs_to :user
  belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :name, :country, :experience, :category_id, :continent_id, presence: true
  validates :name, uniqueness: true
  belongs_to :continent
  belongs_to :category
  has_many :comments
  has_many :my_places_lists
  has_many :users, through: :my_places_lists
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, :password, presence: true
  validates :username, uniqueness: true
  has_many :comments
  has_many :my_places_lists
  has_many :places, through: :my_places_lists

  enum role: [ :default, :admin ]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < Admin::BaseController
  before_action :current_admin?

  def index
    @places = Place.all
  end

  def update
    if params[:approved] === true
      place = Place.find(params[:id])
      place.update(approved: true)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :current_admin?

  def show
    @users = User.all
    @places = Place.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :current_admin?

  def current_user
  @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize!
    render file: "/public/404" unless current_user && current_admin?
  end

  def current_admin?

    current_user && current_user.role == 1
    #   true
    # else
    #   false
    # end
  end

  # def current_admin?
  #   current_user && current_user.admin?
  # end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @places = Place.where(:category_id => @category.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @place = Place.find(params[:id])
    @comment = Comment.new
  end

  def create
    @place = Place.find(params[:place_id])
    @comment = @place.comments.new(comment_params.merge({user_id: current_user.id}))
    if @comment.save
      flash[:sucess] = "Comment Saved!"
      redirect_to place_path(@place)
    else
      flash[:warning] = "Comment Not Saved!"
      redirect_to place_path(@place)
    end

    # @comment = Comment.new(comment_params)
    # @place = Job.find(params[:place_id])
    # @comment.place_id = params[:place_id]
    #
    # @comment.save
    #
    # redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :body, :user_id, :place_id)
  end

end

app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
  def show
    @continent = Continent.find(params[:id])
    @places = Place.where(:continent_id => @continent.id)
  end
end

app/controllers/my_places_lists_controller.rb
class MyPlacesListsController < ApplicationController
  def new
    @user = current_user
    @my_places_list = MyPlacesList.new
    @places = Place.all
  end

  def create
    @my_places_list = MyPlacesList.new(my_places_list_params)
    @user = current_user
    if @my_places_list.save
      redirect_to user_path(user)
    else
      render :new
    end
  end

  private

  def my_places_list_params
    params.require(:my_places_list).permit(:user_id, :place_id, :visited, :bucket)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
  end

  def about
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
    # @places = Place.where(approved: true)
    @user = current_user
    @continents = Continent.all
    @categories = Category.all
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "Thanks for your recommendation of a great place"
      redirect_to places_path
    else
      render :new
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
  end

  private

  def place_params
    params.require(:place).permit(:name, :country, :experience, :image_path, :category_id, :continent_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to places_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_admin?, except: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to places_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:success] = "Profile updated!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/places/index.html.erb
<% @places.each do |place| %>
  <%= place.name %>
  <%= button_to admin_place_path(place, approved: true) %>
<% end %>

app/views/categories/show.html.erb
<div class="page-title">
  <h1>All Best Places in <%= @category.name %></h1>
</div>
<div class="row">
  <% @places.each do |place| %>
    <div class="col s12 m6 l3">
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="<%= place.image_path %>">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= link_to place.name, place_path(place) %> <br />
            <span class="country">(<%= place.country %>)<i class="material-icons right">+</i></span>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= place.name %><i class="material-icons right">-</i></span>
          <p>Why to go there: </p>
          <p><%= place.experience %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<h3 id="post-comment">Post a Comment</h3>
<%= form_for [ @place, @comment ] do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %><br />
</p>
<p>
  <%= f.label :body %>
  <%= f.text_area :body %><br />
</p>

<p>
  <%= f.submit "Submit" %>
</p>
<% end %>

app/views/continents/show.html.erb
<div class="page-title">
  <h1>All Best Places in <%= @continent.name %></h1>
</div>
<div class="row">
  <% @places.each do |place| %>
    <div class="col s12 m6 l3">
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="<%= place.image_path %>">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= link_to place.name, place_path(place) %> <br />
            <span class="country">(<%= place.country %>)<i class="material-icons right">+</i></span>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= place.name %><i class="material-icons right">-</i></span>
          <p>Why to go there: </p>
          <p><%= place.experience %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  <title>Wanderlust</title>
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="/css/materialize.css">
  <link rel="stylesheet" href="/css/style.css">
</head>
<body>
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Wanderlust</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Places", places_path %></li>
        <li><a href="#">My Bucket List</a></li>
        <li><a href="#">My Profile</a></li>
        <li><%# link_to "My Bucket List", user_my_places_list(current_user) %></li>
        <li><% link_to "My Profile", user_path(current_user) %></li>
      </ul>
    </div>
  </nav>
  <% if current_user %>
    <div class="user-menu"
    <h6>Hi,<%= current_user.username %>! <%# link_to "My Profile", user_path(@user) %>
    <%= link_to "Logout", logout_path, method: :delete %></h6>
    </div>
  <% else %>
    <div class="before-user-menu">
    <%= link_to "Login", login_path %> | <%= link_to "Sign in", new_user_path %>
    </div>
  <% end %>
  <main>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
  </main>
  <footer>
  </footer>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="/js/materialize.js"></script>
</body>
</html>

app/views/my_places_lists/new.html.erb
<h1>Create a Bucket List</h1>

<%= form_for [@user, @my_places_list] do |f| %>
<p>Check the boxes of the places that you want to add to your list.</p>
<p>
  <% collection_check_boxes(:post, :place, Place.all, :id, :name)  %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/pages/about.html.erb
<%= image_tag("wanderlust_quote.jpg", :class => "about_img",:alt => "feet and flip flops on a beach") %>

app/views/pages/homepage.html.erb
<div class= "homepage-image">
  <%= image_tag("wanderlust_wall.jpg", :alt => "world map with word wanderlust on an office wall") %>
</div>

app/views/places/_comment.html.erb
<div class="comments">
  <h3 id="comment-section-title"> Comments</h3>
  <h6>Comment by <%= comment.user.username %></h6>
  <p class="comment-title"><%= comment.title %></p>
  <p class="comment-body">"<%= comment.body %>"</p>
  <p>Posted: <%=comment.created_at.strftime("%m/%d/%Y at %l:%M %P")%></p>
</div>

app/views/places/index.html.erb
<div class="page-title">
  <h1>All Places</h1>
</div>
<div class="row">
  <% @places.each do |place| %>
    <div class="col s12 m6 l3">
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="<%= place.image_path %>">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= link_to place.name, place_path(place) %> <br />
            <span class="country">(<%= place.country %>)<i class="material-icons right">+</i></span>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= place.name %><i class="material-icons right">-</i></span>
          <p>Why to go there: </p>
          <p><%= place.experience %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h5><%= link_to "Suggest a place", new_place_path %></h5>

<div class="continents">
  Continents:
<% @continents.each do |continent| %>
<%= link_to continent.name, continent_path(continent) %> |
<% end %>
</div>

<div class="categories">
  Categories:
<% @categories.each do |category| %>
<%= link_to category.name, category_path(category) %> |
<% end %>
</div>

app/views/places/new.html.erb
<h1 id="suggest-place-title">Suggest a new place</h1>
<%= form_for @place do |f| %>
<p>
<%= f.label :name %>
<%= f.text_field :name %><br />
</p>
<p>
<%= f.label :country %>
<%= f.text_field :country %>
</p>
<p>
<%= f.label :continent_id %>
<%= f.collection_select :continent_id, Continent.all, :id, :name, :prompt => 'Please Select a Continent',     class: "form-control" %>
</p>
<p>
<%= f.label :experience %>
<%= f.text_field :experience %>
</p>
<p>
<%= f.label :category_id %>
<%= f.collection_select :category_id, Category.all, :id, :name, :prompt => 'Please Select a Category',     class: "form-control" %>
</p>

<p>
<%= f.submit "Suggest Place" %>

<% end %>

app/views/places/show.html.erb
<div class="page-title" id ="show-title">
  <h1><%= @place.name %></h1>
</div>

<div class="card card-indiv">
  <div class="card-image card-image-indiv waves-effect waves-block waves-light">
    <img class="activator" src="<%= @place.image_path %>">
  </div>
  <div class="card-content">
    <span class="card-title activator grey-text text-darken-4"><i class="material-icons right"></i></span>
    <div class="content-card">
      <p>Country: <%= @place.country %></p>
      <p>Continent: <%= link_to @place.continent.name, continent_path(@place.continent) %><br /></p>
      <p>Category: <%= link_to @place.category.name, category_path(@place.category) %><br /></p>
      <p>Experience: <%= @place.experience %></p>
    </div>
  </div>
  <div class="card-reveal">
    <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
    <p>Here is some more information about this product that is only revealed once clicked on.</p>
  </div>
</div>
<div class="comments-block">
  <div class="comments-list">
  <%= render partial: 'places/comment', collection: @place.comments.reverse %>
  </div>
  <div class="comment-form">
  <%= render partial: 'comments/form' %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.text_field :password %>

<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render partial: 'form' %>

app/views/users/new.html.erb
<h1>Create a new account</h1>

<%= render partial: 'form' %>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="page-title">
    <h1>User profile</h1>
  </div>

  <h5>Name: <%= @user.username %></h5>

  <%= link_to "Edit Profile", edit_user_path(@user) %><br />

  <%= link_to "Delete Account", user_path(@user), method: :delete, :confirm => "Are you sure you want to delete your account?" %>

  <h5>My Bucket List</h5>
  <%= link_to "Create Bucket List", new_user_my_places_list_path(@user) %>

  <h5> Visited Places List</h5>
  <%= link_to "Create Visited Places List", new_user_my_places_list_path(@user) %>
</div>